[ChatOllama]
base_url = "http://localhost:11434"
project_name = "Sonic RNY-80C"
model_name = "rabbit"
temperature = 0.2
top_p = 0.5
top_k = 30

[help]
help = """
欢迎使用Sonic RNY-80C!
你可以通过以下方式与该网安机器人进行交流:
注:对于中括号内的文字，如:[用户id],即直接输入用户id即可。

-operate [用户id]:针对用户操作
-l [用户id] -operate [消息id]:针对指定用户指定会话进行操作
-ls:直接列出所有用户

operate指令:
-l :加载
-ls :列出列表
-d :删除
-n :新建(不支持空格分割id名)
"""

[bert]
model_name = "bert-base-uncased"

[pattern]
logo = """
                        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣤⣴⣦⣦⣦⣦⣦⣦⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣦⣿⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣧⣯⣷⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣿⣿⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣯⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣶⣿⣯⣯⣿⣯⣯⣯⣯⣿⣯⣯⣯⣿⣯⣿⣿⣿⣯⣯⣿⣯⣯⣿⣯⣯⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣿⢏⣿⣿⣯⣯⣯⣯⣿⣯⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡗⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠓⣿⣏⣿⣿⠁⠀⠑⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣄⢘⣧⢻⣿⠀⠀⠀⢁⣿⣟⣿⣿⣿⠉⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠲⣤⣿⠀⣿⠀⠀⠀⠀⠉⣗⢏⣿⠏⢀⣬⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⠙⣏⣤⣾⣿⣿⣯⡟⠒⠒⠀⠀⠀⢢⣶⢞⣯⣷⣤⠈⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⠗⣿⠋⠁⣶⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⢀⣧⣿⣿⣷⢻⣶⣛⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⢼⣿⣿⣿⣿⡟⢿⣿⣿⢖⠀⢀⠀⢙⣛⣉⢟⠀⠀⠀⠀⠀⠀⠀⠀⠙⠟⢟⣿⠀⢸⢁⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⠘⢈⣿⣿⢖⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀    ⢎⣿⡟⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⡀⢖⢸⣿⣗⣖⠀⠀  \\\\         \\\\   ⢀⢧⣿⣿⣿⣿
                        ⠀⠀⠀⠀⠀⠀⣿⢻⣿⣿⣿⣶⣄⣿⣷⣗⢆⠀⠀⠀⠀⠀⠀⠀⠒⠉⠉⠒⠀⠀⠀⠀  ⢀⠋⣿⣏⣾⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⣿⠀⢻⣿⣿⣿⣿⣿⣿⣿⣷⣖⣄⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣷⣶⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⣿⣀⠀⠉⠻⣿⣿⣿⣿⣿⣿⣿⣷⣶⣄⢄⢀⠀⠀⠀⠀⠀⢀⢀⣤⣶⣿⣿⣿⣿⣿⣿⡿⠁⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⠀⢿⣭⣭⣿⣿⣿⣿⠿⢿⠿⣿⣿⢓⠃⠇⢧⣶⣤⣤⣖⣯⣿⣿⣿⣿⣿⣿⣿⣿⠭⠖⠒⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣷⠀⢉⣤⣦⣗⠀⠀⠀⠀⠁⠀⠀⣇⠀⠀⠀⣾⣿⣿⣿⣿⣶⣶⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⣀⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣇⣯⣯⣿⣿⣿⣦⣴⣷⣿⣿⣯⣷⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠀⣠⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣏⣯⣿⣿⣿⣿⣿⣿⣿⣶⡀⣴⣿⣿⣿⣿⣿⣿⣦⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀
                        ⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠟⠗⠗

███████╗ ██████╗ ███╗   ██╗██╗ ██████╗    ██████╗ ███╗   ██╗██╗   ██╗     █████╗  ██████╗  ██████╗    
██╔════╝██╔═══██╗████╗  ██║██║██╔════╝    ██╔══██╗████╗  ██║╚██╗ ██╔╝    ██╔══██╗██╔═████╗██╔════╝    
███████╗██║   ██║██╔██╗ ██║██║██║         ██████╔╝██╔██╗ ██║ ╚████╔╝     ╚█████╔╝██║██╔██║██║         
╚════██║██║   ██║██║╚██╗██║██║██║         ██╔══██╗██║╚██╗██║  ╚██╔╝      ██╔══██╗████╔╝██║██║         
███████║╚██████╔╝██║ ╚████║██║╚██████╗    ██║  ██║██║ ╚████║   ██║       ╚█████╔╝╚██████╔╝╚██████╗    
╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝ ╚═════╝    ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝        ╚════╝  ╚═════╝  ╚═════╝    
by du511
输入-h查看基本操作信息 输入q退出程序                                                                                            
"""
welcome = """
░▒█░░▒█░▒█▀▀▀░▒█░░░░▒█▀▀▄░▒█▀▀▀█░▒█▀▄▀█░▒█▀▀▀░░░█
░▒█▒█▒█░▒█▀▀▀░▒█░░░░▒█░░░░▒█░░▒█░▒█▒█▒█░▒█▀▀▀░░░▀
░▒▀▄▀▄▀░▒█▄▄▄░▒█▄▄█░▒█▄▄▀░▒█▄▄▄█░▒█░░▒█░▒█▄▄▄░░░▄
"""